language: scala

sudo: required
dist: trusty
services: docker

addons:
  apt:
    packages:
      - shellcheck

jdk:
  - openjdk11

scala:
  - 2.12.12

env:
  - EXASOL_DOCKER_VERSION="6.2.15-d1"
  - EXASOL_DOCKER_VERSION="7.0.10"

before_install:
  - git fetch --tags
  - docker pull "exasol/docker-db:$EXASOL_DOCKER_VERSION"
  - docker pull localstack/localstack:0.12.5
  - docker pull alluxio/alluxio:2.5.0

script:
  - ./scripts/ci.sh

after_success:
  - ./sbtx coveralls

cache:
  directories:
    - "$HOME/.sbt/1.0"
    - "$HOME/.sbt/boot/scala*"
    - "$HOME/.sbt/cache"
    - "$HOME/.sbt/launchers"
    - "$HOME/.ivy2"
    - "$HOME/.coursier"

before_cache:
  - du -h -d 1 $HOME/.ivy2/
  - du -h -d 2 $HOME/.sbt/
  - du -h -d 4 $HOME/.coursier/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
  - find $HOME/.coursier/cache -name "*.lock" -type f -delete
